### PR TITLE
Use thriftrw

### LINKED ISSUE #43: Unhelpful error message
```
/usr/lib/node_modules/tcap/node_modules/thriftify/specs/amap.js:38
        throw new Error('key type has to be TYPE.STRING; received %d', ktype.t
              ^
Error: key type has to be TYPE.STRING; received %d
```

Looks like the string substitution here doesn't work the way we might expect it to.

### PR DESCRIPTION
**Pull request by kriskowal**
This change brings tcap into the modern era of ThriftRW including support for annotations, typedefs, and includes.

Fixes #43 #44 

r @leizha @jsu1212 @pwillett

### CODE REVIEW

**Comment by kriskowal** [comment]
Tests fail because pcap headers are unavailable on TravisCI.

**Comment by Raynos** [comment]
@kriskowal can we add `sudo apt-get install pcap-dev` to travis to run tests ?

**Comment by kriskowal** [comment]
@Raynos yeah, trying that out in #46. @pwillett, thank you for the review.

**Comment by pwillett** [comment]
Sure thing, pardon the eager merge clickness - a mistake of distracted attention.

**Pull request merged**
