### PR TITLE
add timestamps to high level output lines

### PR DESCRIPTION
**Pull request by benfleis**
https://github.com/uber/tcap/issues/38

formatted as epoch.ms, could add a prettier formatter if desired.

### CODE REVIEW

**Comment by kriskowal** [comment]
lgtm

**Comment by ShanniLi** [comment]
@benfleis can you paste the output after the change?

**Comment by benfleis** [comment]
Quick and dirty output (post too-fast fixes):
```
ts=1443031537.930 session=0 127.0.0.1:49843 <-- 127.0.0.1:9595 frame=9 type=0x04 Ok ???
...
ts=1443031537.932 session=0 ended src=127.0.0.1:49843 --> dst=127.0.0.1:9595 on lo0
```

If not opposed to the formatting, could use tcpdump style of `13:25:03.931` for timestamp as well, but I kept it numeric for now.

**Comment by ShanniLi** [comment]
1. I am curious that what is the user scenario of adding timestamps. The timestamps are when frames are printed out. It isn't really better than a counter.
2. Maybe move the ts field to a tailer position. It is not very informative at the head of the line. session id is more important.
3. when some flag is used (e.g., '-r'), the frames may be printed out of order, so the timestamp may look strange.

**Comment by benfleis** [comment]
@ShanniLi 
1. When debugging a live protocol problem, counters don't tell me anything relative to multiple side-by-side, external processes. Timestamps do, even if approximate.
2. I put it there in the same model as tcpdump. I think if it's end of line, it will have inconsistent alignment and be less useful. (Also had it after session id in my private version, so I also think that makes sense.)
3. The less naive version would keep ts when frame comes in, and use that. I found this super useful as-is, but could definitely be improved that way.

**Comment by ShanniLi** [comment]
sounds good. :+1:

**Pull request merged**
